### PR TITLE
Enhance Checker

### PR DESCRIPTION
**Pull request by JuliaSprenger**
This PR improves the checker by
- fixing incompatibilities between the BEP specs and the rules
- making the authorized and mandatory folder rules more consistent across levels
- adding a test (dataset) with a complete set of metadata files

### CODE REVIEW

**Review by SylvainTakerkart — APPROVED** [review]
So here, you changed the rules and the checking mecanisms so that everything happens at the current level (instead of having a mix of the current and the "next" level during an iteration...), right? If so, thanks, this is nice!

All this LGTM!

**Comment by JuliaSprenger** [comment]
Yes, that was exactly the idea. Before we still had accidentally listed an `exp-` folder  in the rules and the removal of this required this bigger cleanup and reorganization...

**Comment by SylvainTakerkart** [comment]
actually, it was not accidental... but it was guided by something that's not in the BIDS-animal-ephys specs, which is the naming of the top-level directory with exp-XXX ; this is something I'd like to keep if possible... any idea what we could do about this?

**Comment by SylvainTakerkart** [comment]
could we add an extra rule (the one on the exp-XXX top-level folder)? and this rule would be checked only for internal INT use with a flag to be added on the command line? it's not very clean, but it would do the job...

actually, I'm not sure what to think about this... it probably relates to what we want to do with DigLab2AnDO and the AnDOGenerator... shall we discuss this in the next few days?

**Comment by JuliaSprenger** [comment]
I thin this should be part of the DigLab2AnDO code and AnDO itself should be only dealing with the AnDO specs. Maybe we can have a utility validation function in the DigLab2AnDO repo that is running the AnDO validation and some additional INT specific checks, like the `exp-` parent folder.

**Comment by SylvainTakerkart** [comment]
OK, this makes sense, let's go this way!

**Pull request merged**
