### PR TITLE
Fix session labels

### LINKED ISSUE #75: Fix outdated test folder names
Some sessions folders still follow an old naming scheme `ses-00000000_land_001`, that is not valid in BIDS.

### PR DESCRIPTION
**Pull request by JuliaSprenger**
Fixes #75 and updates the test datasets correspondingly.

### CODE REVIEW

**Review by Slowblitz — APPROVED** [review]

**Review by SylvainTakerkart — COMMENTED** [review]
Those changes are ok for me!

Shall we fix at the same time the problem in our rules that @satra pointed out yesterday, i.e that a session named 'ses-Peter_MS21_180720_110037_concat' (as present in @bendichter 's dataset) should not be validated because of the presence of the _ characters... ?

**Comment by SylvainTakerkart** [comment]
> Those changes are ok for me!
> 
> Shall we fix at the same time the problem in our rules that @satra pointed out yesterday, i.e that a session named 'ses-Peter_MS21_180720_110037_concat' (as present in @bendichter 's dataset) should not be validated because of the presence of the _ characters... ?

or is it actually the goal of this PR? (sorry, havn't been closely enough in what this PR does, ahah ;) )

**Comment by JuliaSprenger** [comment]
Yes, that is exactly what is fixed with this PR for our test datasets and the validator. I also left a comment in #73 that addresses the issue there.

**Comment by SylvainTakerkart** [comment]
awesome! merging...

**Pull request merged**
